### Calculate the combined angular momentum of the solar system. Imagine the solar system condenses to become a black hole, find the radius.

The calculations will be performed with many assumptions and approximations. 
The gaseous planets and the sun will be treated as spheres of uniform density, and their orbits will be treated as circular.
We will assume that no angular momentum is lost during the gravitational collapse. The Sun can't become a black hole, or even a neutron star, due to its low mass. To become a neutron star it needs to be above the Chandrasekhar limit of $1.4 M_{sun}$

### Equations
The total angular momentum (L) is the sum of the orbital L and rotational L of all objects in the solar system.
$L_{tot} = \Sigma L_{orb} + \Sigma L_{rot}$

Since this is conserved, we set this equal to the product of the black hole's moment of inertia $I = M R^2$ and its angular speed $ \omega$.  $L_{tot} = I \omega = M R^2 \omega $  where M is the total mass and R is the radius.

The equations for radial acceleration is $a_{rad} = \dfrac{v^2}{R} = \omega^2 R$ and gravitational acceleration is $a_{grav} = G \dfrac{M}{R^2}$ with gravitational constant G.

The gravitational acceleration at the surface needs to exceed the centripetal acceleration for a rotating object to remain bound. We will set these accelerations equal, then rearranging we get $R^3 = \dfrac{G M}{\omega^2}$. 

We can substitute the angular speed from the conservation of angular momentum relation above and solve for R to obtain $R = \dfrac{L_{tot}^2}{G M^3}$

In [1]:
import numpy as np
import pandas as pd

#some constants
G = 6.67e-11 #m^3 kg^-1 s^-2
c = 2.997e8 #m/s

# source for moment of inertia for black hole https://physics.stackexchange.com/questions/310881/do-black-holes-have-a-moment-of-inertia

#defining functions, the output will be in units of meters, seconds, kilograms
def AngM(m,v,r):
    return (m*1e24)*(v*1e3)*(r*1e9)
def RotAngM(m,r,p):
    return 4*np.pi*(m*1e24)*(0.5*r*1e3)**2/(5*p*3600)
def Radius(L,M):
    return L**2/(G*(M*1e24)**3)

In [2]:
#importing the data and creating a table
df = pd.read_html("https://nssdc.gsfc.nasa.gov/planetary/factsheet/", header = 0, index_col=0)[0][:-1].T
df.drop('MOON', inplace=True)
df = df.apply(pd.to_numeric, errors = 'ignore') #just convert number strings to numeric, ignore others
df

,Mass (1024kg),Diameter (km),Density (kg/m3),Gravity (m/s2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (106 km),Perihelion (106 km),Aphelion (106 km),Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (degrees),Orbital Eccentricity,Obliquity to Orbit (degrees),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
MERCURY,0.3300,4879,5427,3.7,4.3,1407.6,4222.6,57.9,46.0,69.8,88.0,47.4,7.0,0.205,0.034,167,0,0,No,Yes
VENUS,4.8700,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,108.9,224.7,35.0,3.4,0.007,177.400,464,92,0,No,No
EARTH,5.9700,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,152.1,365.2,29.8,0.0,0.017,23.400,15,1,1,No,Yes
MARS,0.6420,6792,3933,3.7,5.0,24.6,24.7,227.9,206.6,249.2,687.0,24.1,1.9,0.094,25.200,-65,0.01,2,No,No
JUPITER,1898.0000,142984,1326,23.1,59.5,9.9,9.9,778.6,740.5,816.6,4331.0,13.1,1.3,0.049,3.100,-110,Unknown*,79,Yes,Yes
SATURN,568.0000,120536,687,9.0,35.5,10.7,10.7,1433.5,1352.6,1514.5,10747.0,9.7,2.5,0.057,26.700,-140,Unknown*,82,Yes,Yes
URANUS,86.8000,51118,1271,8.7,21.3,-17.2,17.2,2872.5,2741.3,3003.6,30589.0,6.8,0.8,0.046,97.800,-195,Unknown*,27,Yes,Yes
NEPTUNE,102.0000,49528,1638,11.0,23.5,16.1,16.1,4495.1,4444.5,4545.7,59800.0,5.4,1.8,0.011,28.300,-200,Unknown*,14,Yes,Yes
PLUTO,0.0146,2370,2095,0.7,1.3,-153.3,153.3,5906.4,4436.8,7375.9,90560.0,4.7,17.2,0.244,122.500,-225,0.00001,5,No,Unknown

In [3]:
col = ['Mass (1024kg)', 'Orbital Velocity (km/s)', 'Distance from Sun (106 km)', 'Diameter (km)', 'Rotation Period (hours)']
df1 = df[col]
df1 = df1.apply(pd.to_numeric, errors = 'ignore')#converting strings to numbers

#Adding the sun to the list of objects
sun = pd.DataFrame([[1.98855e6, 0, 0, 1.3927e6, 590.4]], columns = col, index = ['SUN'])
df1 = pd.concat([df1,sun])

df1['Orbital AngM (kg m^2/s)'] = AngM(df1['Mass (1024kg)'], df1['Orbital Velocity (km/s)'], df1['Distance from Sun (106 km)'])
df1['Rotational AngM (kg m^2/s)'] = RotAngM(df1['Mass (1024kg)'], df1['Diameter (km)'], df1['Rotation Period (hours)']) 

Ltot = df1['Orbital AngM (kg m^2/s)'].sum() + df1['Rotational AngM (kg m^2/s)'].sum() #total angular momentum
Mtot = df1['Mass (1024kg)'].sum() #total mass

#adding column for percent of total angular momentum of the solar system
df1['Ltot'] = 100*(df1['Orbital AngM (kg m^2/s)'] + df1['Rotational AngM (kg m^2/s)'])/Ltot
df1

,Mass (1024kg),Orbital Velocity (km/s),Distance from Sun (106 km),Diameter (km),Rotation Period (hours),Orbital AngM (kg m^2/s),Rotational AngM (kg m^2/s),Ltot
MERCURY,3.300000e-01,47.4,57.9,4879.0,1407.6,9.056718e+38,9.740330e+29,0.002776
VENUS,4.870000e+00,35.0,108.2,12104.0,-5832.5,1.844269e+40,-2.135057e+31,0.056539
EARTH,5.970000e+00,29.8,149.6,12756.0,23.9,2.661474e+40,7.093863e+33,0.081592
MARS,6.420000e-01,24.1,227.9,6792.0,24.6,3.526114e+39,2.101225e+32,0.010810
JUPITER,1.898000e+03,13.1,778.6,142984.0,9.9,1.935895e+43,6.840900e+38,59.350350
SATURN,5.680000e+02,9.7,1433.5,120536.0,10.7,7.898012e+42,1.346094e+38,24.213145
URANUS,8.680000e+01,6.8,2872.5,51118.0,-17.2,1.695464e+42,-2.301528e+36,5.197735
NEPTUNE,1.020000e+02,5.4,4495.1,49528.0,16.1,2.475901e+42,2.712397e+36,7.590315
PLUTO,1.460000e-02,4.7,5906.4,2370.0,-153.3,4.052972e+38,-9.336514e+28,0.001243
SUN,1.988550e+06,0.0,0.0,1392700.0,590.4,0.000000e+00,1.140204e+42,3.495495

In [4]:
print(Radius(Ltot,Mtot)/1000)
print(2*G*Mtot*1e24/c**2)

2020.5359000642127
2957.3372503683754

### Results
The calculated radius is 2020 kilometers, or about 1/3 of Earth's radius, and is closer to the radius of a white dwarf.

This is a contrast to the Schwarzschild radius $ R_s = 2 G M /c^2 = 2.957$ kilometers.

The angular momentum for each planet as a percent of the total in the solar system is shown below.

The Sun only accounts for 3.5% of the total, while Jupiter and Saturn combined have 83.5%.

In [5]:
print("Angular momentum as a percent of the total in the solar system: \n")
print(df1['Ltot'])

Angular momentum as a percent of the total in the solar system:

MERCURY     0.002776
VENUS       0.056539
EARTH       0.081592
MARS        0.010810
JUPITER    59.350350
SATURN     24.213145
URANUS      5.197735
NEPTUNE     7.590315
PLUTO       0.001243
SUN         3.495495
Name: Ltot, dtype: float64